[package]
name = "tx"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
chain-ops.workspace = true

anyhow.workspace = true
cosmrs.workspace = true
tokio.workspace = true

[lints]
workspace = true
