[workspace]
members = [
    "semver",
    "chain-comms",
    "market-data-feeder",
    "alarms-dispatcher",
]

resolver = "2"

[workspace.package]
edition = "2021"
license = "Apache-2.0"

[workspace.dependencies]
semver = { path = "./semver" }
chain-comms = { path = "./chain-comms" }

[patch.crates-io]
cosmrs = { git = "https://github.com/cosmos/cosmos-rust.git", rev = "aef5c708e6dddeec4ad1ba2672c7874a40b9bfc1" }
tendermint = { git = "https://github.com/nolus-protocol/tendermint-rs.git" }
tendermint-rpc = { git = "https://github.com/nolus-protocol/tendermint-rs.git" }

[profile.release]
overflow-checks = true
lto = "fat"
