hard_gas_limit = 1_975_000

[oracles]
osmosis-osmosis-usdc_axelar = "nolus1zvqqf8d6v9ty5enqztgdevdcls8qtxdgccj5mhahj06mqgz3ztwqlez27r"
neutron-astroport-usdc_axl = "nolus1r0d8a3u558h9nswatgafsafnt5hg5h3lqn2pm6lxkph5fevtqfyqs33ruk"

[providers.osmosis_osmosis_usdc_axelar]
name = "osmosis"
oracle_id = "osmosis-osmosis-usdc_axelar"

[providers.neutron_astroport_usdc_axl]
name = "astroport"
oracle_id = "neutron-astroport-usdc_axl"

[comparison_providers]
